window: add OnBackAnimationCallback and BackEvent
Google Camera implements the API 34 predictive-back callback while the activity
is in onPostCreate. Without the class that is a NoClassDefFoundError that takes
the rest of that callback chain with it.

(cherry picked from commit 6e899f21939602b55f992597393db121c641bc5d)
(cherry picked from commit e4132c518c0973e6e56f9b27a80e238bdacd991a)